version: '3'

services: 

  app:
    build: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 100s ./.docker/entrypoint.sh  
    volumes: 
      - .:/var/www
    networks:
      - app-network
    depends_on: 
      - db
      - redis

  nginx:
    ## local do arquivo de build
    build: .docker/nginx    
    container_name: nginx
    ## se cair deve reiniciar?
    restart: always
    ## está autorizado a entrar no terminal do container
    tty: true
    ports:
        #minhaporta : porta container
      - "8000:80"
    volumes: 
      - .:/var/www
    networks: 
      - app-network
    depends_on: 
      - app
  
  db:
    build: .docker/mysql   
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports: 
      - "3306:3306"
    volumes: 
      - ./.docker/dbdata:/var/lib/mysql
    
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - app-network
    

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge
